### ISSUE TITLE
Inconsistency between `pause_code` data type expected by the `pauseCode()` function and the actual data type in the database 

### ISSUE THREAD

**Issue by CarlosSifuentes** [masterfermin02/vicidial-api-wrapper#14]
Hello,  

I have found an inconsistency between the data type expected by the `pauseCode()` method and the actual data type stored in the database.  

### Details:  
- **Affected Interface**: `AgentContract`  
- **Affected Class**: `Agent`  
- **Method**: `pauseCode(string $agentUser, int $code): string`  

The `pauseCode()` method currently defines the second argument (`$code`) as an **int** in both the `AgentContract` interface and the `Agent` class. However, in the database, the `pause_code` field is a **varchar**. This creates a problem because the method does not accept a **string**, which is the actual data type used to store pause codes.  

### Affected Code Example:  
**AgentContract**:  
```php  
public function pauseCode(string $agentUser, int $code): string;  
```  

**Agent**:  
```php  
public function pauseCode(string $agentUser, int $code): string {  
    // Implementation  
}  
```  

### Problem:  
The `pause_code` field in the database is defined as:  
```sql  
pause_code varchar(6) NOT NULL  
```  
This implies that the value of `pause_code` is a string, but the method signature in the API expects an int. Passing the expected value (a string) results in a type error in PHP because the method signature does not match the actual data type of the database field.  

### Proposed Solution:  
Change the signature of the `pauseCode()` method in both the `AgentContract` interface and the `Agent` class to accept a **string** instead of an **int**, as follows:  
```php  
public function pauseCode(string $agentUser, string $code): string;  
```  
This will ensure that the method signature is consistent with the actual data type in the database.  

### Steps to Reproduce:  
1. Call the `pauseCode()` method passing a value of type `string` as `$code`.  
2. Observe the type mismatch error.  

### Environment:  
- **Operating System**: Rocky Linux  
- **PHP Version**: 8.3  
- **`vicidial-api-wrapper` Version**: 3.0.1  

I appreciate the work and effort put into this library, and I hope this contribution is helpful. I am available for any additional information if needed.

**Comment by masterfermin02** [comment]
Thank you very much! I just merge a fix for this
