### ISSUE TITLE
Test tinker

### ISSUE THREAD

**Issue by masterfermin02** [masterfermin02/vicidial-api-wrapper#4]
@phptinker
```php
echo 'Testing tinker :)'
```

**Comment by phptinker** [comment]
@masterfermin02, here's the evaluated code:

```
Testing tinker :)
```

<details>
<summary>We evaluated this code</summary>

```php
echo 'Testing tinker :)'
```
</details>

Check out [Tinkerwell](https://tinkerwell.app) for even easier code evaluation.
