### ISSUE TITLE
Field values are urlencoded in Vicidial

### ISSUE THREAD

**Issue by scicali** [masterfermin02/vicidial-api-wrapper#5]
When you add a lead, fields, like address1, are urlencoded in Vicidial

php 7.4
vicidial svn 3529

Vicidial do not urldecoded query params

**Comment by masterfermin02** [comment]
It working fine for me can you give me more details about your issue? The response should be something like this:
```
SUCCESS: add_lead LEAD HAS BEEN ADDED - 18002474747|999|8|-5|apiuser
```
My Example code
```
require_once './vendor/autoload.php';

use Vicidial\Api\Wrapper\Admin\Client;

$fields['first_name'] = "John";
$fields['last_name']  = "Doe";
$fields['address1']   = "123 Fake St";
$fields['phone_number']   = "18002474747";

try {
    $agent_api = new Client("10.0.0.15", "apiuser", "apipass", "test", false);
    echo $agent_api->add_lead($fields);
} catch (Exception $e) {
    echo 'Exception: ', $e->getMessage(), "\n";
}
```

**Comment by scicali** [comment]
It working, but in address1 field I found urlencoded value: 123+Fake+St

**Comment by masterfermin02** [comment]
On which function are you having this issue? it's working as expected for me
<img width="447" alt="Screen Shot 2023-02-01 at 10 07 06 AM" src="https://user-images.githubusercontent.com/4625540/216065318-3716bd63-ffdc-412b-8465-820e8abc61de.png">

**Comment by scicali** [comment]
I have "123+Fake+St" in address1

Can be some Vicidial settings to adjust? Wich svn version have you tested?

![2023-02-01](https://user-images.githubusercontent.com/62660196/216066852-64892014-71d9-4b94-8bd6-62756de82e8c.png)

**Comment by masterfermin02** [comment]
I'm using :
```
Version:	2.14b0.5
SVN Version:	3677
```

**Comment by scicali** [comment]
Have you set Use Non-Latin(UTF-8): 1 in system settings?
I'll try to upgrade

**Comment by masterfermin02** [comment]
I have `Use Non-Latin(UTF-8)` setup to 0

**Comment by scicali** [comment]
`Use Non-Latin(UTF-8) setup to 0`
work with address1 = "123 Fake St"

`Use Non-Latin(UTF-8) setup to 0 or 1`
not work with ascii extended: address1 = "123 Fàkè S't"

I've extend Vicidial\Api\Wrapper\Admin\Client class and ovverride run method to disable urlencode. That would be wonderful to add urlencode public property to class, so user can set or not urlencode

**Comment by masterfermin02** [comment]
Thanks, I added new change for that:
```
 use Vicidial\Api\Wrapper\Admin\Client;

    $fields['first_name'] = "John";
    $fields['last_name']  = "Doe";
    $fields['address1']   = "123 Fake St";
    $fields['phone_number']   = "18002474747";
    
    try {
        $agent_api = new Client("10.0.0.15", "apiuser", "apipass", "test", false);
        echo $agent_api
        ->withUrlEncode(true)
        ->add_lead($fields);
    } catch (Exception $e) {
        echo 'Exception: ', $e->getMessage(), "\n";
    }
```

**Comment by scicali** [comment]
Wonderful! Thanks you too
