### ISSUE TITLE
Installing package on php7.4 resulted in local package conflict with guzzlehttp/guzzle ^7.2

### ISSUE THREAD

**Issue by AbdulazizFayez** [masterfermin02/vicidial-api-wrapper#6]
Hi, 

I was installing the package using the Php 7.4+ option, using command: 

`composer require "masterfermin02/vicidial-api-wrapper:1.0.3" --with-all-dependencies -W`

i got this on my machine (Windows 10 | Composer v2.5.1| Php 7.4.33):

```bash
./composer.json has been updated
Running composer update masterfermin02/vicidial-api-wrapper --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires masterfermin02/vicidial-api-wrapper 1.0.3 -> satisfiable by masterfermin02/vicidial-api-wrapper[v1.0.3].
    - masterfermin02/vicidial-api-wrapper v1.0.3 requires guzzlehttp/guzzle ^7.2 -> found guzzlehttp/guzzle[dev-master, 7.2.0, ..., 7.5.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (^6.5).

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

2. Updated my current `guzzlehttp/guzzle` to ^7.2 as per requested above, i got this:

```bash
./composer.json has been updated
Running composer update masterfermin02/vicidial-api-wrapper --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - php-http/guzzle6-adapter[v2.0.0, ..., 2.x-dev] require guzzlehttp/guzzle ^6.0 -> found guzzlehttp/guzzle[6.0.0, ..., 6.5.x-dev] but it conflicts with your root composer.json require (^7.2).
    - Root composer.json requires php-http/guzzle6-adapter ^2.0 -> satisfiable by php-http/guzzle6-adapter[v2.0.0, v2.0.1, v2.0.2, 2.x-dev].


Installation failed, reverting ./composer.json to its original content.
```

I am stuck with this as package `php-http/guzzle6-adapter` depends on older version of 6.2 for `guzzlehttp/guzzle`

Please advise.

**Comment by masterfermin02** [comment]
Hello @AbdulazizFayez  `php-http/guzzle6-adapter` had a version 7 https://packagist.org/packages/php-http/guzzle7-adapter you could use that instead to fix the issue. 
Remove `php-http/guzzle6-adapter`
Then install the version 7
`composer require php-http/guzzle7-adapter`

**Comment by AbdulazizFayez** [comment]
Hi @masterfermin02 After long trials finally solved my problem😁

Its weird that none of the issues i came across online related to my issue has mentioned about this🧐.. _now its time to test the codes integrating it into my project._

Thank you very much and apologies for late feedback!! 🙏
