### ISSUE TITLE
Php Version

### ISSUE THREAD

**Issue by muratyilmaz-dev** [masterfermin02/vicidial-api-wrapper#7]
Hi,
PHP version after Vicibox 10 installation: PHP Version 7.4.6
After installing vicidial-api-wrapper, I called a test file. I got a warning like this:

**Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.4.15". You are running 7.4.6. in /srv/www/htdocs/vendor/composer/platform_check.php on line 24**

Since it is a minor version,
Will there be a problem if I change the relevant value in this file to 70406?

**if (!(PHP_VERSION_ID >= 70415)) {**

Thanks.

**Comment by masterfermin02** [comment]
Yes should work, but I recommend running the SDK on a PHP version number 8+ because PHP ended support for 7.4 last year and will stop supporting 8.0 this year. You can run SDK on a separate server with the later version of PHP, for example.
