### ISSUE TITLE
variable error 'string moh_list'

### ISSUE THREAD

**Issue by muratyilmaz-dev** [masterfermin02/vicidial-api-wrapper#8]
I tested the example/admin/moh_list.php file.

Fatal error: Uncaught BadMethodCallException: Method moh_list does not exist

i got the error.

**/src/Admin/Client.php on line 69**

Error in expression **'string moh_list'**

Changing it to **'moh_list'** fixed the error.

**Comment by masterfermin02** [comment]
Thank you I will create a PR to fix
